### ISSUE TITLE
RcppEigen 0.3.4.0.0 preparations

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppEigen#103]
NB:  This (old) initial entry is outdated.  Best to scroll to the bottom.  As of late Feb 2024 we are down to three affected packages out of well over 400.

----

So with #102 (thanks again, @yixuan, for preparing it) we have a release candidate for RcppEigen 0.3.4.0.0.   It is currently running a first pass of reverse depends, and a few packages do indeed go belly up.

I suggest we pool resources between myself, @zdebruine, @yixuan, @bbolker ... and whoever wants and can help! Maybe some of the `rstan` folks want to pitch in?

~While the reverse depends run is still 'cooking' we have failures of these packages (and I will edit/complete this as it finishes)~  The run is now done (and fully summarized in [this commit](https://github.com/RcppCore/rcpp-logs/commit/02456486f78f3e0bc256d082915b2751d90b4f1a)).  We should focus on these ten failures out of 329 packages tested:

- [ ] ctsem (at https://github.com/cdriveraus/ctsem) (no fix :disappointed: but maintainer emailed)
- [x] Eagle (at https://github.com/cran/Eagle mirroring http://eagle.r-forge.r-project.org/) (patch emailed 2021-11-23) (merged 2021-11-29, on CRAN 2021-11-30)
- [ ] eimpute (at https://github.com/cran/eimpute, actual upstream source unclear) (patch emailed 2021-11-23)
- [ ] fssemR  (at https://github.com/Ivis4ml/fssemR) ([PR #3](https://github.com/Ivis4ml/fssemR/pull/3) filed 2021-11-23) (heard back 2021-12-15, see below)
- [ ] gRbase (at https://github.com/hojsgaard/gRbase) ([PR #9](https://github.com/hojsgaard/gRbase/pull/9) filed 2021-11-26)
- [ ] groupedSurv (at https://github.com/cran/groupedSurv/, actual upstream source unclear) (patch emailed 2021-11-26)
- [ ] OpenMx (at https://github.com/OpenMx/OpenMx) ([PR #332](https://github.com/OpenMx/OpenMx/pull/332) filed 2021-11-27) (merged 2021-11-30)
- ~RAINBOWR~ (unrelated to RcppEigen, see below)
- [x] RMixtCompIO (at https://github.com/modal-inria/MixtComp) (no fix :disappointed: but maintainer emailed, fixed upstream 2022-01-14, on CRAN 2022-01-17)
- [ ] skpr (at https://github.com/tylermorganwall/skpr) ([PR #65](https://github.com/tylermorganwall/skpr/pull/65) filed 2021-12-05, merged 2022-03-23)

~Let's not despair---as I write this 191 have passes, or 20x more than those few failures. (I also skipped three)~

It would best if volunteers could step forward and pick package to adopt for a fix.  A release candidate version of RcppEigen is in the Rcpp drat repo and be installed via `install.packages("RcppEigen", repo="https://RcppCore.github.io/drat")` (and you may have to set `type="source"`, I generally don't on Linux).

If you adopt a package, comment below and edit your comment as you move along, eventually (ideally) showing a PR to the package you adopted.  We can get this done---it is a matter of effectively parcelling out the grunt work.  Let's do this.


The error summary (committed as usual to the [rcpp-logs](https://github.com/RcppCore/rcpp-logs/)  repo) is

```
Test of RcppEigen 0.3.3.99.0 had 316 successes, 13 failures, and 3 skipped packages.                                                                                                                               
Ran from 2021-10-26 15:15:22.92 to 2021-10-27 00:09:34.52 for 8.903 hours                                                                                                                                          
Average of 96.541 secs relative to 575.519 secs using 6 runners                                                                                                                                                    
                                                                                                                                                                                                                   
Failed packages:  breathteststan, ctsem, Eagle, eimpute, fssemR, fwildclusterboot, gRbase, groupedSurv, OpenMx, RAINBOWR, RMixtCompIO, SEMgraph, skpr                                                              
                                                                                                                                                                                                                   
Skipped packages:  hBayesDM, kmcudaR, nlmixr                                                                                                                                                                       
                                                                                                                                                                                                                   
None still working                                                                                                                                                                                                 
                                                                                                                                                                                                                   
None still scheduled                                                                                                                                                                                               
                                                                                                                                                                                                                   
Error summary:                                                                                                                                                                                                     
             package                missingPkg badInstall error fail warn note ok hasOtherIssue                                                                                                                    
 1:   breathteststan                                FALSE     0    0    0   14  0         FALSE  possibly unrelated numeric errors                                                                                 
 2:            ctsem                                 TRUE     0    0    1   13  0         FALSE  error: no matching function for call to ‘isinf(const stan::math::var&)'                                           
 3:            Eagle                                 TRUE     0    0    0    4 10         FALSE  error: no match for ‘operator=’                                                                                   
 4:          eimpute                                 TRUE     0    0    0   13  1         FALSE  error: no match for ‘operator/’                                                                                   
 5:           fssemR                                 TRUE     0    0    0   13  1         FALSE  error: no match for ‘operator=’                                                                                   
 6: fwildclusterboot                                FALSE     0    0    0    0 14         FALSE  possibly unrelated numeric errors                                                                                 
 7:           gRbase                                 TRUE     0    0    0    6  8         FALSE  error: static assertion failed: cannot convert type to SEXP                                                       
 8:      groupedSurv                                 TRUE     0    0    0    4 10         FALSE  error: cannot convert ‘Eigen::internal::enable_if<.....                                                           
 9:           OpenMx                                 TRUE     1    0    0   13  0          TRUE  error: no match for ‘operator-’                                                                                   
10:         RAINBOWR                                 TRUE     3    0    0    2  9         FALSE  unrelated: "Error: object ‘get_aes_var’ is not exported by 'namespace:rvcheck'"                                   
11:      RMixtCompIO                                 TRUE     0    0    0    4 10         FALSE  error: static assertion failed:                                                                                   
12:         SEMgraph 'cate', 'diffusr', 'flip'         NA     0    0    0    1 13         FALSE  passes once installed                                                                                             
13:             skpr                                 TRUE     0    0    0    4 10         FALSE  error: cannot convert ‘Eigen::internal::enable_if<....                    
```

I have skipped the package that passed once its dependencies were added and two with apparently unrelated test error. That leaves ten _which failed to install_ under 0.3.3.99.0 which is surely something we need to address if we want the package on CRAN.

**Comment by zdebruine** [comment]
@eddelbuettel @bbolker I'm personally invested in seeing this happen (my RcppML package would make good use of Eigen 3.4), and happy to help, but I'm in the first week of my postdoc and a novice compared to all you experts.  It'll be a few weeks before I can give this what it needs.

**Comment by jdblischak** [comment]
> Ah, the CRAN version of Eagle is actually ahead (2.4.5) of the GitHub version (1.0) of Eagle (davidaknowles/eagle), from which I had forked and installed.

@zdebruine I just wanted to jump in real quick to clear up some confusion. The versions are different because these are 2 different packages:

* [Eagle](http://eagle.r-forge.r-project.org/) is on [CRAN](https://cran.r-project.org/package=Eagle) and the source is hosted on [R-Forge](https://r-forge.r-project.org/projects/eagle/)
* [eagle](https://github.com/davidaknowles/eagle) is a GitHub-only project. While it has RcppEigen as a dependency, it is not blocking CRAN submission because it's not on CRAN

**Comment by eddelbuettel** [comment]
I just tried to look into Eagle and failed on 

https://github.com/cran/Eagle/blob/aa31d13ff2d9181712798e994c567b2f6b0004e4/src/calculate_a_and_vara_batch_rcpp.cpp#L164

which majorly upset the template programming in Eigen and I have not found an easy way auto (via a temporary variable). Anybody?

**Comment by eddelbuettel** [comment]
Ok, took another stab and I have both Eagle and fssemR sorted out. Bboth were a "simple" case of needing a cast for one of the row or col indices (computed from another Eigen expression) and I will create PRs.  ctsem is more of a mystery, maybe someone from team rstan can take a look (hi, @SteveBronder).

**Comment by eddelbuettel** [comment]
Two quick updates:

1. We have the first updated package, the winner is `Eagle`.  

2. And as we heard from a second, `groupedSurv` the fix I often made (`static_cast<int>()` for indices) is due to use of, say, `VectorXd` where `VectorXi` would be better. I think I may even have seen a hint of  'no longer accept `double` for indices' in the Eigen 3.4.0 release notes but did not realize this when preparing the patch.  So if you read this as an (Rcpp)Eigen user, check that the indexing comes from `VectorXi`.

**Comment by eddelbuettel** [comment]
I have completed one pass and managed to create seven out of nine patch sets. I had to bail on `ctsem` (maybe @bgoodri and @SteveBronder can take a look?) as well as on `RMixtCompIO` (anybody ?).  Second looks would be appreciated as would be gentle nags in due time to get the PRs and patches onto CRAN.

**Comment by bgoodri** [comment]
I will look at it. ctsem is one of the more complicated packges that uses
Stan.

**Comment by cdriveraus** [comment]
I'm just aware of this now, happy to try modify the stan code in ctsem but also not sure where to start. I'm available for any discussion / ideas @bgoodri ...

**Comment by eddelbuettel** [comment]
@cdriveraus Yep, I didn't email you til yesterday so no need to feel guilty :)   And as you can see other packages "need to move too".  As `ctsem` is ineed far from simply, help by @bgoodri and friends will be very much appreciated.

**Comment by bgoodri** [comment]
I can confirm that the compilation error with the ctsem package and Eigen 3.4 is not due to anything specific to ctsem. The same error 

> no known conversion for argument 1 from ‘const stan::math::var’ to ‘float’  611 |   isnan(float __x)

(and similarly for `isinf`) can be triggered more simply just by executing
```
rstan::stan_model(model_code =
"
functions {
  vector get_eigenvalues(matrix A) {
    return eigenvalues_sym(A);
  }
}
parameters {
  cov_matrix[2] A;
}
model {
  vector[2] a = get_eigenvalues(A);
}
")
```
Stan definitely has implementations of `isinf` and `isnan` for its var types at

https://github.com/stan-dev/math/blob/develop/stan/math/rev/core/std_isinf.hpp#L16
https://github.com/stan-dev/math/blob/develop/stan/math/rev/core/std_isnan.hpp#L18

the problem is likely that those file are not getting included early enough. Stan's rev.hpp metaheader looks like

```
#ifndef STAN_MATH_REV_HPP
#define STAN_MATH_REV_HPP

#include <stan/math/prim/fun/Eigen.hpp> // first because of the Eigen plugin and then includes Eigen/Dense

#include <stan/math/opencl/rev.hpp>

#include <stan/math/rev/core.hpp> // includes var definition and isinf, isnan, etc.
#include <stan/math/rev/meta.hpp>
#include <stan/math/rev/fun.hpp>
#include <stan/math/rev/functor.hpp>

#include <stan/math/prim.hpp> // includes eigenvalues_sym etc.

#endif
```

If that is correct, then this is definitely Stan's fault, but at the moment I don't know how to fix it without breaking our Eigen plugin. I also don't know how we got away with this under the previous versions of Eigen. @SteveBronder @andrjohns

**Comment by eddelbuettel** [comment]
Maybe making (more explicit) use of `namespace` possibly conditional behind a C++17 define (_i.e._ something like

```c++
#if  __cplusplus > 201703L
```

then you do not defone `isinf`, and hence do not clash?   (Untest, obviously)

**Comment by bgoodri** [comment]
I think the issue with `isinf` and `isnan` would be fixed if I updated StanHeaders on CRAN. More recent versions of Stan put `isinf` and `isnan` in the std namespace so that the implementations for Stan's reverse mode var custom scalar type can be found by ADL. But the (much) older version of StanHeaders on CRAN defines them in the stan::math namespace and then ultimately calls `std::isinf` on the `double` value underlying the `var` type.

I have been planning for ages to update StanHeaders on CRAN anyway, but doing so requires a lot of patching to make it backwards compatible with the CRAN packages that use it. We have achieved backwards compatibility on everything but Windows, but then got sidetracked because some package that has rstan in its Suggests wrote a bad test that crashed R and CRAN wants me to upload a new rstan that is more user-proof. Unfortunately, I think the StanHeaders that I want to get Windows-compatible and onto CRAN will expose another issue with how Stan solves a triangular system of equations under Eigen 3.4 that I will need to figure out a workaround for.

TL;DR: If ctsem becomes the last package blocking RcppEigen, I'll upload a minor update to StanHeaders that just fixes the `isinf` and `isnan` thing.

**Comment by Ivis4ml** [comment]
I have fixed that and merged the fixed into the fssemR on github now. Will work on submit a new version of package onto CRAN later.

**Comment by eddelbuettel** [comment]
I ran another set today, first against [RcppEigen at CRAN](https://github.com/RcppCore/rcpp-logs/blob/master/results/rcppeigen/RcppEigen-20211225-1.txt) and then second against the RcppEigen release candidate for with Eigen 3.4.0:

```
Test of RcppEigen 0.3.3.99.0 had 323 successes, 17 failures, and 2 skipped packages. 
Ran from 2021-12-25 23:35:31.69 to 2021-12-26 08:57:16.51 for 9.362 hours 
Average of 98.552 secs relative to 588.151 secs using 6 runners

Failed packages:  BigDataStatMeth, breathteststan, ctsem, eimpute, fssemR, fwildclusterboot, gRbase, groupedSurv, OpenMx, PReMiuM, RAINBOWR, RMixtCompIO, secr, SEMgraph, skpr, stan4bart, TDA 

Skipped packages:  hBayesDM, nlmixr 

None still working

None still scheduled

Error summary:
             package missingPkg badInstall error fail warn note ok hasOtherIssue
 1:  BigDataStatMeth                 FALSE     7    0    0    6  0          TRUE  not us, issues at CRAN
 2:   breathteststan                 FALSE     0    0    0   13  0         FALSE  not us, minor (?) recurring numeric test error
 3:            ctsem                  TRUE     0    0    0   13  0         FALSE  help needed with known Eigen 3.4.0 issue
 4:          eimpute                  TRUE     0    0    0   12  1         FALSE  patch emailed 2021-11-23
 5:           fssemR                  TRUE     0    0    0   12  1         FALSE  pr filed, merged, but not at CRAN yet
 6: fwildclusterboot                 FALSE     0    0    0    0 13         FALSE  flaky, small numerical error
 7:           gRbase                  TRUE     0    0    0    6  7         FALSE  pr filed 2021-11-26
 8:      groupedSurv                  TRUE     0    0    0    4  9         FALSE  patch emailed 2021-11-26
 9:           OpenMx                  TRUE     0    0    0   13  0          TRUE  pr filed 2021-11-27, merged 2021-11-30, but not at CRAN yet
10:          PReMiuM                  TRUE     0    0    0    4  9         FALSE  known flaky
11:         RAINBOWR                  TRUE     2    0    0    3  8         FALSE  not us, Error: object ‘get_aes_var’ is not exported by 'namespace:rvcheck'  
12:      RMixtCompIO                  TRUE     0    0    0    4  9         FALSE  maintainer emailed  
13:             secr                  TRUE     9    0    0    4  0         FALSE  known BH issues, needs one std::isnan
14:         SEMgraph                  TRUE    10    0    0    3  0         FALSE  not us, "Error: object ‘ggm_compare’ is not exported by 'namespace:GGMncv'"
15:             skpr                  TRUE     0    0    0    4  9         FALSE  pr file 2021-12-05
16:        stan4bart                  TRUE     0    0    0    4  9         FALSE  help needed
17:              TDA                  TRUE    10    0    0    3  0         FALSE  known BH issue, upstream contacted
```

We have two packages with merged changes that should be at CRAN at some point.  But a number of packages have either not yet responded, or do not even have a fix. 
- `ctsem` is difficult and a known open issue
- `stan4bart` could likely benefit from someone from the stan look into it too
- some of the other packages might benefit from a nudge to the maintainer.   
 
In short, if you want to see this package updated at CRAN, please consider adopting a task.  A message here should be good enough to monitor things.

**Comment by bgoodri** [comment]
I'll talk with @vdorie about stan4bart.

**Comment by Quentin62** [comment]
Hi, the RmixtComp's maintainer emails me today about the eigen problem.  
I'm working on it, this PR should solve the problem https://github.com/modal-inria/MixtComp/pull/20

**Comment by Quentin62** [comment]
I think I solved the problem (I tested with RcppEigen_0.3.3.99.0).
I will submit it on CRAN in the next days. [Here](https://github.com/RcppCore/RcppEigen/files/7870416/RMixtCompIO_4.0.7.tar.gz) is the archive, if you want to check with your pipeline

**Comment by eddelbuettel** [comment]
Two thumbs up!  It does indeed.  Thanks for taking care of that -- one down (fully once on CRAN).

**Comment by SteveBronder** [comment]
Sorry Stan has taken forever to sort this out. We just figured out the commit in the Eigen repo that caused our regression tests to fail. We're currently sorting out whether this is a Stan issue or Eigen issue. For anyone who wants to follow along the discussion is [here](https://github.com/stan-dev/math/pull/2583#issuecomment-1293761592)

**Comment by eddelbuettel** [comment]
See #123 -- help with RcppEigen towards Eigen 3.4.0 would be greatly appreciated.

**Comment by bgoodri** [comment]
My impression is that Stan is good with either version of Eigen, but I am preparing to push another StanHeaders to CRAN, so I will run the reverse dependency checks with both versions of RcppEigen.

**Comment by andrjohns** [comment]
> My impression is that Stan is good with either version of Eigen, but I am preparing to push another StanHeaders to CRAN, so I will run the reverse dependency checks with both versions of RcppEigen.

StanHeaders 2.26 isn't compatible (would need [this PR](https://github.com/stan-dev/math/pull/2888)), but 2.32 is fine

**Comment by andrjohns** [comment]
I've run the reverse-dependency checks locally, and there are now only a handful of packages which aren't compatible. The current status is summarised below:

Package | Action | Merged 
-- | -- | --
eimpute | [PR Opened](https://github.com/Mamba413/eimpute/pull/1)
FastJM | [PR Opened](https://github.com/shanpengli/FastJM/pull/2) | x
GAGAs | No public repo, emailed maintainer
JMH | [PR Opened](https://github.com/shanpengli/JMH/pull/1) | x
lme4 | [RcppEigen CHOLMOD issue](https://github.com/RcppCore/RcppEigen/pull/131#issuecomment-1894224522) |
nebula | [PR Opened](https://github.com/lhe17/nebula/pull/41)
OpenMx |[RcppEigen CHOLMOD issue](https://github.com/RcppCore/RcppEigen/pull/131#issuecomment-1894224522) |  
PartialNetwork | [PR Opened](https://github.com/ahoundetoungan/PartialNetwork/pull/4)
RAINBOWR | [PR Opened](https://github.com/KosukeHamazaki/RAINBOWR/pull/9)
svines | [PR Opened](https://github.com/tnagler/svines/pull/3)

**Comment by eddelbuettel** [comment]
Confirming. Running the patch 3.4.0 branch, I get a similar list on a full reverse-depends run. 

Without `approxOT`, and no `lme4` or `OpenMx` due to fix but with TDA (known issue from BH update). Wicked cool that you opened these PRs!  This is a suitably small list so I think we should pursue this 'with proper deadline' and maybe look at a, say, March update.

**Comment by eddelbuettel** [comment]
Here is a bit of `data.table` wrangling I found helpful in the long-running (and now completed!) quest to update RcppArmadillo:

```r
> library(data.table)
> db <- data.table(tools::CRAN_package_db())
> pkgs <- c("approxOT", "eimpute", "FastJM", "GAGAs", "JMH", "nebula", "PartialNetwork", "RAINBOWR", "svines")
> db[Package %in% pkgs,.(Package,Version,Date,Published)][order(-Published)]
          Package Version       Date  Published
           <char>  <char>     <char>     <char>
1:          GAGAs   0.6.2       <NA> 2024-01-23
2:         svines   0.2.3       <NA> 2024-01-18
3:       approxOT     1.1 2024-01-15 2024-01-16
4:         FastJM   1.4.1 2024-01-06 2024-01-09
5:       RAINBOWR  0.1.33       <NA> 2023-09-12
6: PartialNetwork   1.0.2 2023-09-01 2023-08-22
7:         nebula   1.4.2 2023-07-03 2023-07-05
8:            JMH   1.0.2 2023-06-07 2023-06-15
9:        eimpute   0.2.2 2022-10-22 2022-10-22
> 
```

leading to a shortrt (yay!) list of open tickets:

```r
> pkgs <- c("approxOT", "eimpute", "FastJM", "JMH", "nebula", "PartialNetwork", "RAINBOWR")
> db[Package %in% pkgs,.(Package,Version,Date,Published)][order(-Published)]
          Package Version       Date  Published
           <char>  <char>     <char>     <char>
1:       approxOT     1.1 2024-01-15 2024-01-16
2:         FastJM   1.4.1 2024-01-06 2024-01-09
3:       RAINBOWR  0.1.33       <NA> 2023-09-12
4: PartialNetwork   1.0.2 2023-09-01 2023-08-22
5:         nebula   1.4.2 2023-07-03 2023-07-05
6:            JMH   1.0.2 2023-06-07 2023-06-15
7:        eimpute   0.2.2 2022-10-22 2022-10-22
> 
```

**Comment by eddelbuettel** [comment]
One shorter set of failures on another rev.dep run:  eimpute, FastJM, JMH, nebula, PartialNetwork, RAINBOWR.

```r
> library(data.table)
data.table 1.15.0 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
> db <- data.table(tools::CRAN_package_db())
> pkgs <- c("eimpute", "FastJM", "JMH", "nebula", "PartialNetwork", "RAINBOWR")
> db[Package %in% pkgs,.(Package,Version,Date,Published)][order(-Published)]
          Package Version       Date  Published
           <char>  <char>     <char>     <char>
1:         FastJM   1.4.1 2024-01-06 2024-01-09
2:       RAINBOWR  0.1.33       <NA> 2023-09-12
3: PartialNetwork   1.0.2 2023-09-01 2023-08-22
4:         nebula   1.4.2 2023-07-03 2023-07-05
5:            JMH   1.0.2 2023-06-07 2023-06-15
6:        eimpute   0.2.2 2022-10-22 2022-10-22
> 
```

**Comment by eddelbuettel** [comment]
Ran another reverse dependency check after making a small change in the main branch.  Unchanged: same six packages failing.  I am now going to send an email to the five distinct maintainers of these packages, reminding them of the PRs kindly prepared by @andrjohns and proposing an actual release _two weeks from now_ on Feb 28.

**Comment by eddelbuettel** [comment]
`nebula` was just updated on CRAN!  So we are down to five.

```r
> library(data.table)
data.table 1.15.0 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
> db <- data.table(tools::CRAN_package_db())
> pkgs <- c("eimpute", "FastJM", "JMH", "PartialNetwork", "RAINBOWR")
> db[Package %in% pkgs,.(Package,Version,Date,Published)][order(-Published)]
          Package Version       Date  Published
           <char>  <char>     <char>     <char>
1:         FastJM   1.4.1 2024-01-06 2024-01-09
2:       RAINBOWR  0.1.33       <NA> 2023-09-12
3: PartialNetwork   1.0.2 2023-09-01 2023-08-22
4:            JMH   1.0.2 2023-06-07 2023-06-15
5:        eimpute   0.2.2 2022-10-22 2022-10-22
> 
```

**Comment by yixuan** [comment]
I suspect that the email of the original maintainer of `eimpute` is no longer valid, and I have just sent an email to other authors of the package (the emails listed in `DESCRIPTOIN` are also out-dated, and I happen to know their new addresses). Hope we get some response in the next few days.

**Comment by eddelbuettel** [comment]
Agreed that that is problematic, but CRAN has a way of taking care of it. I have seen a number of packages from the Rcpp nexus disappear in the last few weeks (often over simple `size_t` compiler warnings and whatnot -- but no response leads to removal).

I am really thankful for the work you and @andrjohns did: it is time we get to 3.4.0. If only five packages are in the way among well over 400 using RcppEigen then it is worth proceeding.  

That said, let's reach out as best as we can.  That several of the PRs were merged is good too. `eimpute` and `PartialNetwork` appear to be the only ones without a (visible, to me) response so far.

**Comment by eddelbuettel** [comment]
@yixuan Now confirmed as I got email from Zhe Gao, now at USTC.  `eimpute` has been updated and submitted to CRAN so we may be down to four soon.

**Comment by yixuan** [comment]
Yeah I also received an update email from Zhe. Seems we have moved one step forward!

**Comment by eddelbuettel** [comment]
Yes indeed.  The possible 'shrapnel' is now under 1% -- 4 out of over 400 packages.  And they all have merged.  This will, after all, work out and quite smoothly.

Nice when patience pays off.  Thanks again for your persistent help all along!

**Comment by eddelbuettel** [comment]
And now on CRAN:

![image](https://github.com/RcppCore/RcppEigen/assets/673121/cbaf9a04-b67d-4bb8-bbcc-8f58dbc92d58)

**Comment by eddelbuettel** [comment]
Now JMH is on CRAN too so we are down to three:

```r
> library(data.table)
data.table 1.15.0 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
> db <- data.table(tools::CRAN_package_db())
> pkgs <- c("FastJM", "PartialNetwork", "RAINBOWR")
> db[Package %in% pkgs,.(Package,Version,Date,Published)][order(-Published)]
          Package Version       Date  Published
           <char>  <char>     <char>     <char>
1:         FastJM   1.4.1 2024-01-06 2024-01-09
2:       RAINBOWR  0.1.33       <NA> 2023-09-12
3: PartialNetwork   1.0.2 2023-09-01 2023-08-22
> 

```

**Comment by eddelbuettel** [comment]
It has been shipped to CRAN.  :crossed_fingers:

**Comment by eddelbuettel** [comment]
> Thanks, on its way to CRAN.

Yay yay yay!   Huge huge thank you to all who help, especially @yixuan @andrjohns @jaganmn !

**Comment by eddelbuettel** [comment]
And `FastJM` just updated (thanks, @shanpengli !) so we are really down to two affected, and those have PRs too.
